/* eslint-disable */
/**
 * GENERATED FILE - DO NOT EDIT MANUALLY.
 *
 * Source: PriusChat custom PIDs spreadsheet (Vincent1449p) - Metric sheet.
 * Sheet: Metric
 * URL: https://docs.google.com/spreadsheets/d/1Mmlb-SHATQBuTa_3tORdKQatSbvdIouEdMZcasXJghk/gviz/tq?tqx=out:csv&sheet=Metric
 * Retrieved: 2026-02-10
 *
 * To regenerate: node scripts/generate-priuschat-metric.mjs
 */

import type { PidDefinition } from '../../types/obd';
import { compileTorqueEquation } from '../torqueEquation';

export interface PriusChatMetricRow {
  name: string;
  shortName: string;
  modeAndPid: string;
  equation: string;
  min: number;
  max: number;
  units: string;
  header: string;
}

export const PRIUSCHAT_METRIC_ROWS: PriusChatMetricRow[] = [
  {
    name: "FR Wheel Speed",
    shortName: "FR WS",
    modeAndPid: "2103",
    equation: "A * 32 / 25",
    min: 0,
    max: 200,
    units: "km/h",
    header: "7B0",
  },
  {
    name: "FL Wheel Speed",
    shortName: "FL WS",
    modeAndPid: "2103",
    equation: "B * 32 / 25",
    min: 0,
    max: 200,
    units: "km/h",
    header: "7B0",
  },
  {
    name: "RR Wheel Speed",
    shortName: "RR WS",
    modeAndPid: "2103",
    equation: "C * 32 / 25",
    min: 0,
    max: 200,
    units: "km/h",
    header: "7B0",
  },
  {
    name: "RL Wheel Speed",
    shortName: "RL WS",
    modeAndPid: "2103",
    equation: "D * 32 / 25",
    min: 0,
    max: 200,
    units: "km/h",
    header: "7B0",
  },
  {
    name: "Deceleration Sensor",
    shortName: "DecelSen",
    modeAndPid: "2105",
    equation: "A * 36.36 / 255 - 18.18",
    min: -18.18,
    max: 18.18,
    units: "m/s2",
    header: "7B0",
  },
  {
    name: "Deceleration Sensor2",
    shortName: "DecelSen2",
    modeAndPid: "2105",
    equation: "B * 36.36 / 255 - 18.18",
    min: -18.18,
    max: 18.18,
    units: "m/s2",
    header: "7B0",
  },
  {
    name: "Yaw Rate Sensor",
    shortName: "YR1",
    modeAndPid: "2106",
    equation: "A - 128",
    min: -128,
    max: 127,
    units: "degrees/s",
    header: "7B0",
  },
  {
    name: "Yaw Rate Sensor2",
    shortName: "YR2",
    modeAndPid: "2106",
    equation: "B - 128",
    min: -128,
    max: 127,
    units: "degrees/s",
    header: "7B0",
  },
  {
    name: "Steering Angle Sensor",
    shortName: "SteerSen",
    modeAndPid: "2106",
    equation: "(C * 256 + D) / 10 - 3276.8",
    min: -720,
    max: 720,
    units: "degrees",
    header: "7B0",
  },
  {
    name: "Wheel Cylinder Pressure Sensor",
    shortName: "WC Pres",
    modeAndPid: "2107",
    equation: "A / 51",
    min: 0,
    max: 5,
    units: "V",
    header: "7B0",
  },
  {
    name: "Reservoir Warning SW",
    shortName: "BrkFluid",
    modeAndPid: "211D",
    equation: "{A:6}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7B0",
  },
  {
    name: "Main Idle SW",
    shortName: "IdleSW",
    modeAndPid: "211D",
    equation: "{A:5}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7B0",
  },
  {
    name: "Stop Light SW",
    shortName: "StpSW",
    modeAndPid: "211F",
    equation: "{A:7}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7B0",
  },
  {
    name: "Parking Brake SW",
    shortName: "PKBSW",
    modeAndPid: "211F",
    equation: "{A:6}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7B0",
  },
  {
    name: "Vehicle Speed_7B0",
    shortName: "KPH_7B0",
    modeAndPid: "2121",
    equation: "A * 326.4 / 255",
    min: 0,
    max: 200,
    units: "km/h",
    header: "7B0",
  },
  {
    name: "Stop Light Relay Output",
    shortName: "StpRelay",
    modeAndPid: "213C",
    equation: "{A:7}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7B0",
  },
  {
    name: "ABS Warning Light",
    shortName: "ABS",
    modeAndPid: "213D",
    equation: "{A:7}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7B0",
  },
  {
    name: "Brake Warning Light",
    shortName: "BrkWarn",
    modeAndPid: "213D",
    equation: "{A:6}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7B0",
  },
  {
    name: "Slip Indicator Light",
    shortName: "Slip",
    modeAndPid: "213D",
    equation: "{A:5}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7B0",
  },
  {
    name: "Buzzer",
    shortName: "Buzzer",
    modeAndPid: "213D",
    equation: "{A:4}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7B0",
  },
  {
    name: "ECB Warning Light",
    shortName: "ECB",
    modeAndPid: "213D",
    equation: "{A:1}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7B0",
  },
  {
    name: "FR Wheel Acceleration",
    shortName: "FR WA",
    modeAndPid: "2142",
    equation: "( A - {A:7} * 256 ) * 199.27 / 127",
    min: -10,
    max: 10,
    units: "m/s2",
    header: "7B0",
  },
  {
    name: "FL Wheel Acceleration",
    shortName: "FL WA",
    modeAndPid: "2142",
    equation: "( B - {B:7} * 256 ) * 199.27 / 127",
    min: -10,
    max: 10,
    units: "m/s2",
    header: "7B0",
  },
  {
    name: "RR Wheel Acceleration",
    shortName: "RR WA",
    modeAndPid: "2142",
    equation: "( C - {C:7} * 256 ) * 199.27 / 127",
    min: -10,
    max: 10,
    units: "m/s2",
    header: "7B0",
  },
  {
    name: "RL Wheel Acceleration",
    shortName: "RL WA",
    modeAndPid: "2142",
    equation: "( D - {D:7} * 256 ) * 199.27 / 127",
    min: -10,
    max: 10,
    units: "m/s2",
    header: "7B0",
  },
  {
    name: "Zero Point of Decele",
    shortName: "0Decel",
    modeAndPid: "2146",
    equation: "A * 50.02 / 255 - 25.11",
    min: -25.11,
    max: 24.91,
    units: "m/s2",
    header: "7B0",
  },
  {
    name: "Zero Point of Decele2",
    shortName: "0Decel2",
    modeAndPid: "2146",
    equation: "B * 50.02 / 255 - 25.11",
    min: -25.11,
    max: 24.91,
    units: "m/s2",
    header: "7B0",
  },
  {
    name: "Zero Point of Yaw Rate",
    shortName: "0Yaw",
    modeAndPid: "2146",
    equation: "C - 128",
    min: -128,
    max: 127,
    units: "degrees/s",
    header: "7B0",
  },
  {
    name: "Zero Point of Steering Angle",
    shortName: "0Steer",
    modeAndPid: "2146",
    equation: "(D * 256 + E) / 10 - 3276.8",
    min: -720,
    max: 720,
    units: "degrees",
    header: "7B0",
  },
  {
    name: "Lateral G",
    shortName: "Lateral G",
    modeAndPid: "2147",
    equation: "A * 50.02 / 255 - 25.11",
    min: -25.11,
    max: 24.91,
    units: "m/s2",
    header: "7B0",
  },
  {
    name: "Forward and Rearward G",
    shortName: "Fwd/Rwd G",
    modeAndPid: "2147",
    equation: "B * 50.02 / 255 - 25.11",
    min: -25.11,
    max: 24.91,
    units: "m/s2",
    header: "7B0",
  },
  {
    name: "Yaw Rate Value",
    shortName: "YR Val",
    modeAndPid: "2147",
    equation: "C - 128",
    min: -128,
    max: 127,
    units: "degrees/s",
    header: "7B0",
  },
  {
    name: "Steering Angle Value",
    shortName: "SteerAngle",
    modeAndPid: "2147",
    equation: "(D * 256 + E) / 10 - 3276.8",
    min: -720,
    max: 720,
    units: "degrees",
    header: "7B0",
  },
  {
    name: "FR Regenerative Request",
    shortName: "RegenReq",
    modeAndPid: "2148",
    equation: "A * 256 + B",
    min: 0,
    max: 400,
    units: "Nm",
    header: "7B0",
  },
  {
    name: "FR Regenerative Operation",
    shortName: "RegenOp",
    modeAndPid: "2148",
    equation: "C * 256 + D",
    min: 0,
    max: 400,
    units: "Nm",
    header: "7B0",
  },
  {
    name: "Regen Cooperation",
    shortName: "RegenCoop",
    modeAndPid: "2158",
    equation: "{A:7}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7B0",
  },
  {
    name: "TRC(TRAC) Ctrl Status",
    shortName: "TRAC",
    modeAndPid: "215A",
    equation: "{A:7}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7B0",
  },
  {
    name: "TRC(TRAC) Engine Ctrl Status",
    shortName: "TRC Eng",
    modeAndPid: "215A",
    equation: "{A:6}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7B0",
  },
  {
    name: "TRC(TRAC) Brake Ctrl Status",
    shortName: "TRC Brk",
    modeAndPid: "215A",
    equation: "{A:5}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7B0",
  },
  {
    name: "FR Wheel VSC Ctrl Status",
    shortName: "FR VSC",
    modeAndPid: "215A",
    equation: "{B:7}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7B0",
  },
  {
    name: "FL Wheel VSC Ctrl Status",
    shortName: "FL VSC",
    modeAndPid: "215A",
    equation: "{B:6}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7B0",
  },
  {
    name: "RR Wheel VSC Ctrl Status",
    shortName: "RR VSC",
    modeAndPid: "215A",
    equation: "{B:5}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7B0",
  },
  {
    name: "RL Wheel VSC Ctrl Status",
    shortName: "RL VSC",
    modeAndPid: "215A",
    equation: "{B:4}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7B0",
  },
  {
    name: "FR Wheel ABS Ctrl Status",
    shortName: "FR ABS",
    modeAndPid: "215F",
    equation: "{A:7}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7B0",
  },
  {
    name: "FL Wheel ABS Ctrl Status",
    shortName: "FL ABS",
    modeAndPid: "215F",
    equation: "{A:6}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7B0",
  },
  {
    name: "RR Wheel ABS Ctrl Status",
    shortName: "RR ABS",
    modeAndPid: "215F",
    equation: "{A:5}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7B0",
  },
  {
    name: "RL Wheel ABS Ctrl Status",
    shortName: "RL ABS",
    modeAndPid: "215F",
    equation: "{A:4}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7B0",
  },
  {
    name: "RR Wheel EBD Ctrl Status",
    shortName: "RR EBD",
    modeAndPid: "215F",
    equation: "{A:1}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7B0",
  },
  {
    name: "RL Wheel EBD Ctrl Status",
    shortName: "RL EBD",
    modeAndPid: "215F",
    equation: "{A:0}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7B0",
  },
  {
    name: "BA Ctrl Status",
    shortName: "BA",
    modeAndPid: "215F",
    equation: "{B:4}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7B0",
  },
  {
    name: "PBA Ctrl Status",
    shortName: "PBA",
    modeAndPid: "215F",
    equation: "{B:3}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7B0",
  },
  {
    name: "Zero Point of Yaw Rate2",
    shortName: "0Yaw2",
    modeAndPid: "21A1",
    equation: "A -128",
    min: -128,
    max: 127,
    units: "degrees/s",
    header: "7B0",
  },
  {
    name: "SLA Solenoid Current",
    shortName: "SLA curr",
    modeAndPid: "21A3",
    equation: "A * 3 / 255",
    min: 0,
    max: 3,
    units: "A",
    header: "7B0",
  },
  {
    name: "SLR Solenoid Current",
    shortName: "SLR curr",
    modeAndPid: "21A3",
    equation: "B * 3 / 255",
    min: 0,
    max: 3,
    units: "A",
    header: "7B0",
  },
  {
    name: "SSC Solenoid Current",
    shortName: "SSC curr",
    modeAndPid: "21A3",
    equation: "C * 3 / 255",
    min: 0,
    max: 3,
    units: "A",
    header: "7B0",
  },
  {
    name: "SCC Solenoid Current",
    shortName: "SCC curr",
    modeAndPid: "21A3",
    equation: "D * 3 / 255",
    min: 0,
    max: 3,
    units: "A",
    header: "7B0",
  },
  {
    name: "SMC Solenoid Current",
    shortName: "SMC curr",
    modeAndPid: "21A3",
    equation: "E * 3 / 255",
    min: 0,
    max: 3,
    units: "A",
    header: "7B0",
  },
  {
    name: "SRC Solenoid Current",
    shortName: "SRC curr",
    modeAndPid: "21A3",
    equation: "F * 3 / 255",
    min: 0,
    max: 3,
    units: "A",
    header: "7B0",
  },
  {
    name: "Inspection Mode (Other=Off,Inspect=On)",
    shortName: "Insp Mode",
    modeAndPid: "21A6",
    equation: "{A:7}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7B0",
  },
  {
    name: "Hazard Switch History (Incomplete=Off,Complete=On)",
    shortName: "Haz Hist",
    modeAndPid: "21BC",
    equation: "{A:5}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7B0",
  },
  {
    name: "FR Speed Open (Normal=0,Error=1)",
    shortName: "FRS Open",
    modeAndPid: "21BE",
    equation: "{A:7}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7B0",
  },
  {
    name: "FL Speed Open (Normal=0,Error=1)",
    shortName: "FLS Open",
    modeAndPid: "21BE",
    equation: "{A:6}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7B0",
  },
  {
    name: "RR Speed Open (Normal=0,Error=1)",
    shortName: "RRS Open",
    modeAndPid: "21BE",
    equation: "{A:5}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7B0",
  },
  {
    name: "RL Speed Open (Normal=0,Error=1)",
    shortName: "RLS Open",
    modeAndPid: "21BE",
    equation: "{A:4}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7B0",
  },
  {
    name: "Yaw Rate Open (Normal=0,Error=1)",
    shortName: "YR Open",
    modeAndPid: "21BE",
    equation: "{A:2}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7B0",
  },
  {
    name: "Deceleration Open (Normal=0,Error=1)",
    shortName: "Decel Open",
    modeAndPid: "21BE",
    equation: "{A:1}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7B0",
  },
  {
    name: "Steering Open (Normal=0,Error=1)",
    shortName: "Steer Open",
    modeAndPid: "21BE",
    equation: "{A:0}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7B0",
  },
  {
    name: "Master Cylinder Open (Normal=0,Error=1)",
    shortName: "MC Open",
    modeAndPid: "21BE",
    equation: "{B:7}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7B0",
  },
  {
    name: "Stroke Open (Normal=0,Error=1)",
    shortName: "Stroke Open",
    modeAndPid: "21BE",
    equation: "{B:5}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7B0",
  },
  {
    name: "FR Wheel Cylinder Open (Normal=0,Error=1)",
    shortName: "FRWC Open",
    modeAndPid: "21BE",
    equation: "{B:3}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7B0",
  },
  {
    name: "Accumulator Open (Normal=0,Error=1)",
    shortName: "Acc Open",
    modeAndPid: "21BE",
    equation: "{C:7}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7B0",
  },
  {
    name: "HV Communication Open (Normal=0,Error=1)",
    shortName: "HVC Open",
    modeAndPid: "21BE",
    equation: "{C:6}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7B0",
  },
  {
    name: "Tail Cancel SW",
    shortName: "Tail Cancel",
    modeAndPid: "2112",
    equation: "{A:5}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7C0",
  },
  {
    name: "P-Seatbelt Buckle SW",
    shortName: "P-Seatbelt",
    modeAndPid: "2112",
    equation: "{B:7}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7C0",
  },
  {
    name: "Check Engine SW",
    shortName: "Pwr SW",
    modeAndPid: "2112",
    equation: "{B:0}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7C0",
  },
  {
    name: "Oil Pressure Switch",
    shortName: "Oil Pres",
    modeAndPid: "2112",
    equation: "{E:4}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7C0",
  },
  {
    name: "+B Voltage Value",
    shortName: "Aux B Volt",
    modeAndPid: "2113",
    equation: "A / 10",
    min: 0,
    max: 20,
    units: "V",
    header: "7C0",
  },
  {
    name: "Vehicle Speed Meter_7C0",
    shortName: "KPH_7C0",
    modeAndPid: "2121",
    equation: "A",
    min: 0,
    max: 199,
    units: "km/h",
    header: "7C0",
  },
  {
    name: "Coolant Temperature_7C0",
    shortName: "Coolant_7C0",
    modeAndPid: "2123",
    equation: "A / 2",
    min: 0,
    max: 127.5,
    units: "C",
    header: "7C0",
  },
  {
    name: "Fuel Input",
    shortName: "Fuel Level",
    modeAndPid: "2129",
    equation: "A / 2",
    min: 0,
    max: 50,
    units: "Liter",
    header: "7C0",
  },
  {
    name: "Distance Since Oil Change for U.S.A. (reset)",
    shortName: "Oil Chg Dist",
    modeAndPid: "2141",
    equation: "A * 2514600 / 15625",
    min: 0,
    max: 41038,
    units: "km",
    header: "7C0",
  },
  {
    name: "Rheostat value (dark=0,bright=255)",
    shortName: "Rheostat",
    modeAndPid: "2168",
    equation: "A",
    min: 0,
    max: 255,
    units: "",
    header: "7C0",
  },
  {
    name: "Key Remind Sound (buzzer/Normal, Fast, Slow)",
    shortName: "KeyBuz",
    modeAndPid: "21A1",
    equation: "A",
    min: 0,
    max: 255,
    units: "",
    header: "7C0",
  },
  {
    name: "Seat Belt Beep Query (Dis A=0,Ena R=32,Ena P=64,Dis D=96,Ena D=128,Dis P=160,192=Dis R,Ena A=160)",
    shortName: "SBB Query",
    modeAndPid: "21A7",
    equation: "A",
    min: 0,
    max: 192,
    units: "",
    header: "7C0",
  },
  {
    name: "Reverse Beep Query (Ena=0,Dis=64)",
    shortName: "RB Query",
    modeAndPid: "21AC",
    equation: "A",
    min: 0,
    max: 64,
    units: "",
    header: "7C0",
  },
  {
    name: "Room Temp Sensor",
    shortName: "Room",
    modeAndPid: "2121",
    equation: "A * 63.75 / 255 - 6.5",
    min: -6.5,
    max: 57.25,
    units: "C",
    header: "7C4",
  },
  {
    name: "Ambient Temp Sensor",
    shortName: "Ambient",
    modeAndPid: "2122",
    equation: "A * 89.25 / 255 - 23.3",
    min: -23.3,
    max: 65.95,
    units: "C",
    header: "7C4",
  },
  {
    name: "Solar Sensor (D side)",
    shortName: "Solar D",
    modeAndPid: "2124",
    equation: "A",
    min: 0,
    max: 255,
    units: "",
    header: "7C4",
  },
  {
    name: "Engine Coolant Temp_7C4",
    shortName: "Coolant_7C4",
    modeAndPid: "2126",
    equation: "A * 89.25 / 255 + 1.3",
    min: 1.3,
    max: 90.55,
    units: "C",
    header: "7C4",
  },
  {
    name: "Set Temperature (D side)",
    shortName: "Set t D",
    modeAndPid: "2129",
    equation: "A / 2 + 17.5",
    min: 17.5,
    max: 32.5,
    units: "C",
    header: "7C4",
  },
  {
    name: "Blower Motor Speed Level",
    shortName: "Blower Level",
    modeAndPid: "213C",
    equation: "A",
    min: 0,
    max: 31,
    units: "",
    header: "7C4",
  },
  {
    name: "Adjusted Ambient Temp",
    shortName: "AdjAmbient",
    modeAndPid: "213D",
    equation: "A * 81.6 / 255 - 30.8",
    min: -30.8,
    max: 50.8,
    units: "C",
    header: "7C4",
  },
  {
    name: "Air Mix Servo Targ Pulse (D)",
    shortName: "A/M STP D",
    modeAndPid: "2141",
    equation: "A",
    min: 0,
    max: 255,
    units: "",
    header: "7C4",
  },
  {
    name: "Air Mix Servo Actual Pulse (D)",
    shortName: "A/M SAP D",
    modeAndPid: "2141",
    equation: "B",
    min: 0,
    max: 255,
    units: "",
    header: "7C4",
  },
  {
    name: "Air Outlet Servo Pulse (D)",
    shortName: "A/O SP D",
    modeAndPid: "2143",
    equation: "A",
    min: 0,
    max: 255,
    units: "",
    header: "7C4",
  },
  {
    name: "Air Outlet Servo Actu Pulse (D)",
    shortName: "A/O SAP D",
    modeAndPid: "2143",
    equation: "B",
    min: 0,
    max: 255,
    units: "",
    header: "7C4",
  },
  {
    name: "Air Inlet Damper Targ Pulse",
    shortName: "A/I DTP",
    modeAndPid: "2144",
    equation: "A",
    min: 0,
    max: 255,
    units: "",
    header: "7C4",
  },
  {
    name: "Air Inlet Damper Actual Pulse",
    shortName: "A/I DAP",
    modeAndPid: "2144",
    equation: "B",
    min: 0,
    max: 255,
    units: "",
    header: "7C4",
  },
  {
    name: "Compressor Speed",
    shortName: "Comp Spd",
    modeAndPid: "2149",
    equation: "A * 256 + B",
    min: 0,
    max: 10000,
    units: "RPM",
    header: "7C4",
  },
  {
    name: "Compressor Target Speed",
    shortName: "Comp T Spd",
    modeAndPid: "214A",
    equation: "A * 256 + B",
    min: 0,
    max: 10000,
    units: "RPM",
    header: "7C4",
  },
  {
    name: "Evaporator Fin Thermistor",
    shortName: "Evap Fin",
    modeAndPid: "214B",
    equation: "A * 89.25 / 255 - 29.7",
    min: -29.7,
    max: 59.55,
    units: "C",
    header: "7C4",
  },
  {
    name: "Evaporator Target Temp",
    shortName: "Evap Tgt",
    modeAndPid: "214C",
    equation: "(A * 256 + B) / 100 - 327.68",
    min: -29.7,
    max: 59.55,
    units: "C",
    header: "7C4",
  },
  {
    name: "Regulator Pressure Sensor",
    shortName: "Reg Pres",
    modeAndPid: "2153",
    equation: "A * 3.75105 / 255 - 0.45668",
    min: -0.45668,
    max: 3.29437,
    units: "MPaG",
    header: "7C4",
  },
  {
    name: "Calculated Load_7E0",
    shortName: "CLoad_7E0",
    modeAndPid: "2101",
    equation: "A * 20 / 51",
    min: 0,
    max: 100,
    units: "%",
    header: "7E0",
  },
  {
    name: "Vehicle Load",
    shortName: "Veh Load",
    modeAndPid: "2101",
    equation: "(B * 256 + C) * 100 / 65535",
    min: 0,
    max: 100,
    units: "%",
    header: "7E0",
  },
  {
    name: "Mass Air Flow",
    shortName: "MAF",
    modeAndPid: "2101",
    equation: "(D * 256 + E) / 100",
    min: 0,
    max: 271,
    units: "gm/sec",
    header: "7E0",
  },
  {
    name: "Manifold Air Pressure_7E0",
    shortName: "MAP_7E0",
    modeAndPid: "2101",
    equation: "F",
    min: 0,
    max: 255,
    units: "kPa",
    header: "7E0",
  },
  {
    name: "Intake Air Temperature_7E0",
    shortName: "IAT_7E0",
    modeAndPid: "2101",
    equation: "G - 40",
    min: -40,
    max: 140,
    units: "C",
    header: "7E0",
  },
  {
    name: "Atmosphere Pressure_7E0",
    shortName: "AtmPres_7E0",
    modeAndPid: "2101",
    equation: "H",
    min: 0,
    max: 255,
    units: "kPa",
    header: "7E0",
  },
  {
    name: "Coolant Temperature_7E0",
    shortName: "Coolant_7E0",
    modeAndPid: "2101",
    equation: "I - 40",
    min: -40,
    max: 120,
    units: "C",
    header: "7E0",
  },
  {
    name: "Engine Speed_7E0",
    shortName: "RPM_7E0",
    modeAndPid: "2101",
    equation: "(J * 256 + K) / 4",
    min: 0,
    max: 6000,
    units: "RPM",
    header: "7E0",
  },
  {
    name: "Vehicle Speed_7E0",
    shortName: "KPH_7E0",
    modeAndPid: "2101",
    equation: "L",
    min: 0,
    max: 160,
    units: "km/h",
    header: "7E0",
  },
  {
    name: "Engine Run Time (Time since Ign-On)",
    shortName: "Ign Time",
    modeAndPid: "2101",
    equation: "M * 256 + N",
    min: 0,
    max: 65535,
    units: "sec.",
    header: "7E0",
  },
  {
    name: "Fuel System Status #1 (OL=1,CL=2,OLDrive=4,OLFault=8,CLFault=16)",
    shortName: "FSS1",
    modeAndPid: "2103",
    equation: "A",
    min: 1,
    max: 16,
    units: "",
    header: "7E0",
  },
  {
    name: "Short FT #1",
    shortName: "Short FT1",
    modeAndPid: "2103",
    equation: "C * 199.2 / 255 - 100",
    min: -100,
    max: 99.2,
    units: "%",
    header: "7E0",
  },
  {
    name: "Long FT #1",
    shortName: "Long FT1",
    modeAndPid: "2103",
    equation: "D * 199.2 / 255 - 100",
    min: -100,
    max: 99.2,
    units: "%",
    header: "7E0",
  },
  {
    name: "IGN Advance",
    shortName: "IGN",
    modeAndPid: "2103",
    equation: "E / 2 - 64",
    min: -64,
    max: 63.5,
    units: "deg",
    header: "7E0",
  },
  {
    name: "Target Air-Fuel Ratio",
    shortName: "TAFR",
    modeAndPid: "2104",
    equation: "(A * 256 + B) * 1.99 / 65535",
    min: 0,
    max: 1.99,
    units: "",
    header: "7E0",
  },
  {
    name: "AF Lambda B1S1",
    shortName: "AFL B1S1",
    modeAndPid: "2104",
    equation: "(C * 256 + D) * 1.99 / 65535",
    min: 0,
    max: 1.99,
    units: "",
    header: "7E0",
  },
  {
    name: "AFS Voltage B1S1",
    shortName: "AFSV B1S1",
    modeAndPid: "2104",
    equation: "(E * 256 + F) * 7.99 / 65535",
    min: 0,
    max: 7.99,
    units: "V",
    header: "7E0",
  },
  {
    name: "MIL",
    shortName: "MIL",
    modeAndPid: "2106",
    equation: "{A:7}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7E0",
  },
  {
    name: "Communication with HV",
    shortName: "HV Comm",
    modeAndPid: "2124",
    equation: "{A:5}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7E0",
  },
  {
    name: "Communication with Brake",
    shortName: "Brk Comm",
    modeAndPid: "2124",
    equation: "{A:3}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7E0",
  },
  {
    name: "Comm with Air Conditioner",
    shortName: "AC Comm",
    modeAndPid: "2124",
    equation: "{A:2}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7E0",
  },
  {
    name: "Initial Engine Coolant Temp",
    shortName: "Init ECT",
    modeAndPid: "2137",
    equation: "A * 159.3 / 255 - 40",
    min: -40,
    max: 119.3,
    units: "C",
    header: "7E0",
  },
  {
    name: "Initial Intake Air Temp",
    shortName: "Init IAT",
    modeAndPid: "2137",
    equation: "B * 159.3 / 255 - 40",
    min: -40,
    max: 119.3,
    units: "C",
    header: "7E0",
  },
  {
    name: "Injection volume (Cylinder 1) for 10 times",
    shortName: "Inj Vol",
    modeAndPid: "213C",
    equation: "(A * 256 + B) * 2.047 / 65535",
    min: 0,
    max: 2.047,
    units: "ml",
    header: "7E0",
  },
  {
    name: "Injection duration for cylinder 1",
    shortName: "Inj Dur",
    modeAndPid: "213C",
    equation: "C * 256 + D",
    min: 0,
    max: 65535,
    units: "micro sec.",
    header: "7E0",
  },
  {
    name: "Total FT #1",
    shortName: "Total FT1",
    modeAndPid: "213C",
    equation: "E * 0.996 / 255 - 0.5",
    min: -0.5,
    max: 0.496,
    units: "",
    header: "7E0",
  },
  {
    name: "VVT Aim Angle #1",
    shortName: "VVTAA1",
    modeAndPid: "2144",
    equation: "(A * 256 + B) * 399.9 / 65535",
    min: 0,
    max: 100,
    units: "%",
    header: "7E0",
  },
  {
    name: "VVT OCV Duty #1",
    shortName: "VVTOCVD1",
    modeAndPid: "2144",
    equation: "(C * 256 + D) * 399.9 / 65535",
    min: 0,
    max: 100,
    units: "%",
    header: "7E0",
  },
  {
    name: "VVT Change Angle #1",
    shortName: "VVTCA1",
    modeAndPid: "2144",
    equation: "(E * 256 + F) * 639.9 / 65535",
    min: 0,
    max: 639.9,
    units: "DegFR",
    header: "7E0",
  },
  {
    name: "Misfire RPM",
    shortName: "MisfireRPM",
    modeAndPid: "2145",
    equation: "B * 25",
    min: 0,
    max: 6375,
    units: "RPM",
    header: "7E0",
  },
  {
    name: "Misfire Load",
    shortName: "MisfireLoad",
    modeAndPid: "2145",
    equation: "C * 3.98 / 255",
    min: 0,
    max: 3.98,
    units: "g/rev",
    header: "7E0",
  },
  {
    name: "Cylinder #1 Misfire Count",
    shortName: "MisfireCnt#1",
    modeAndPid: "2145",
    equation: "D",
    min: 0,
    max: 255,
    units: "",
    header: "7E0",
  },
  {
    name: "Cylinder #2 Misfire Count",
    shortName: "MisfireCnt#2",
    modeAndPid: "2145",
    equation: "E",
    min: 0,
    max: 255,
    units: "",
    header: "7E0",
  },
  {
    name: "Cylinder #3 Misfire Count",
    shortName: "MisfireCnt#3",
    modeAndPid: "2145",
    equation: "F",
    min: 0,
    max: 255,
    units: "",
    header: "7E0",
  },
  {
    name: "Cylinder #4 Misfire Count",
    shortName: "MisfireCnt#4",
    modeAndPid: "2145",
    equation: "G",
    min: 0,
    max: 255,
    units: "",
    header: "7E0",
  },
  {
    name: "All Cylinders Misfire Count",
    shortName: "MisfireCntAll",
    modeAndPid: "2145",
    equation: "H",
    min: 0,
    max: 255,
    units: "",
    header: "7E0",
  },
  {
    name: "Ignition Trig. Count",
    shortName: "IgnTrigCnt",
    modeAndPid: "2145",
    equation: "I * 256 + J",
    min: 0,
    max: 65535,
    units: "",
    header: "7E0",
  },
  {
    name: "EGR Step Position",
    shortName: "EGR Step",
    modeAndPid: "2147",
    equation: "A",
    min: 0,
    max: 120,
    units: "step",
    header: "7E0",
  },
  {
    name: "Requested Engine Torque",
    shortName: "ReqEngTorq",
    modeAndPid: "2149",
    equation: "(A * 256 + B) / 4",
    min: 0,
    max: 73,
    units: "kW",
    header: "7E0",
  },
  {
    name: "HV Target Engine Speed",
    shortName: "TgtEngSpd",
    modeAndPid: "2149",
    equation: "C * 25",
    min: 0,
    max: 5200,
    units: "RPM",
    header: "7E0",
  },
  {
    name: "Actual Engine Torque",
    shortName: "ActEngTorq",
    modeAndPid: "2149",
    equation: "(D * 256 + E) - 32768",
    min: 0,
    max: 150,
    units: "Nm",
    header: "7E0",
  },
  {
    name: "Engine Run Time (Up to 255 sec. only)",
    shortName: "ign sec",
    modeAndPid: "2149",
    equation: "F",
    min: 0,
    max: 255,
    units: "sec.",
    header: "7E0",
  },
  {
    name: "Request Engine Run Time",
    shortName: "ReqEngRun",
    modeAndPid: "2149",
    equation: "G / 10",
    min: 0,
    max: 25.5,
    units: "sec.",
    header: "7E0",
  },
  {
    name: "Judge Time Engine Ignition",
    shortName: "JTEI",
    modeAndPid: "2149",
    equation: "H / 10",
    min: 0,
    max: 25.5,
    units: "sec.",
    header: "7E0",
  },
  {
    name: "Judge Time Engine Output",
    shortName: "JTEO",
    modeAndPid: "2149",
    equation: "I / 10",
    min: 0,
    max: 25.5,
    units: "sec.",
    header: "7E0",
  },
  {
    name: "ISC Learning Value",
    shortName: "ISCLV",
    modeAndPid: "2149",
    equation: "(J * 256 + K) * 79.998 / 65535",
    min: 0,
    max: 79.998,
    units: "L/s",
    header: "7E0",
  },
  {
    name: "Engine Independent Control",
    shortName: "EngIC",
    modeAndPid: "2149",
    equation: "{L:7}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7E0",
  },
  {
    name: "Request Warm-up",
    shortName: "WarmUp",
    modeAndPid: "2149",
    equation: "{L:6}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7E0",
  },
  {
    name: "Racing Operation",
    shortName: "Racing",
    modeAndPid: "2149",
    equation: "{L:5}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7E0",
  },
  {
    name: "Engine Independent",
    shortName: "EngI",
    modeAndPid: "2149",
    equation: "{L:4}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7E0",
  },
  {
    name: "F/C for Engine Stop Req",
    shortName: "FCEngStp",
    modeAndPid: "2149",
    equation: "{L:3}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7E0",
  },
  {
    name: "ISC Learning",
    shortName: "ISCL",
    modeAndPid: "2149",
    equation: "{L:2}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7E0",
  },
  {
    name: "Engine Speed of Cyl #1 (51199 rpm: Active Test not performed)",
    shortName: "RPM#1",
    modeAndPid: "2154",
    equation: "(A * 256 + B) * 51199 / 65535",
    min: 0,
    max: 51199,
    units: "RPM",
    header: "7E0",
  },
  {
    name: "Engine Speed of Cyl #2 (51199 rpm: Active Test not performed)",
    shortName: "RPM#2",
    modeAndPid: "2154",
    equation: "(C * 256 + D) * 51199 / 65535",
    min: 0,
    max: 51199,
    units: "RPM",
    header: "7E0",
  },
  {
    name: "Engine Speed of Cyl #3 (51199 rpm: Active Test not performed)",
    shortName: "RPM#3",
    modeAndPid: "2154",
    equation: "(E * 256 + F) * 51199 / 65535",
    min: 0,
    max: 51199,
    units: "RPM",
    header: "7E0",
  },
  {
    name: "Engine Speed of Cyl #4 (51199 rpm: Active Test not performed)",
    shortName: "RPM#4",
    modeAndPid: "2154",
    equation: "(G * 256 + H) * 51199 / 65535",
    min: 0,
    max: 51199,
    units: "RPM",
    header: "7E0",
  },
  {
    name: "Av Engine Speed of All Cyl (51199 rpm: Active Test not performed)",
    shortName: "RPMavg",
    modeAndPid: "2154",
    equation: "(I * 256 + J) * 51199 / 65535",
    min: 0,
    max: 51199,
    units: "RPM",
    header: "7E0",
  },
  {
    name: "Model Code_7E0",
    shortName: "MCode_7E0",
    modeAndPid: "21C1",
    equation: "ABCDEFG",
    min: 0,
    max: 0,
    units: "",
    header: "7E0",
  },
  {
    name: "Engine Type",
    shortName: "Eng Type",
    modeAndPid: "21C1",
    equation: "HIJKLM",
    min: 0,
    max: 0,
    units: "",
    header: "7E0",
  },
  {
    name: "Cylinder Number",
    shortName: "Cyl#",
    modeAndPid: "21C1",
    equation: "N",
    min: 4,
    max: 4,
    units: "",
    header: "7E0",
  },
  {
    name: "Destination",
    shortName: "dest",
    modeAndPid: "21C1",
    equation: "P",
    min: 0,
    max: 255,
    units: "",
    header: "7E0",
  },
  {
    name: "Model Year",
    shortName: "Model Yr",
    modeAndPid: "21C1",
    equation: "Q + 1900",
    min: 1900,
    max: 2155,
    units: "",
    header: "7E0",
  },
  {
    name: "System Identification",
    shortName: "Sys ID",
    modeAndPid: "21C1",
    equation: "R",
    min: 0,
    max: 0,
    units: "",
    header: "7E0",
  },
  {
    name: "State of Charge",
    shortName: "SoC",
    modeAndPid: "015B",
    equation: "A * 20 / 51",
    min: 30,
    max: 90,
    units: "%",
    header: "7E2",
  },
  {
    name: "Calculated Load_7E2",
    shortName: "CLoad_7E2",
    modeAndPid: "2101",
    equation: "A * 20 / 51",
    min: 0,
    max: 100,
    units: "%",
    header: "7E2",
  },
  {
    name: "Manifold Air Pressure_7E2",
    shortName: "MAP_7E2",
    modeAndPid: "2101",
    equation: "B",
    min: 0,
    max: 255,
    units: "kPa",
    header: "7E2",
  },
  {
    name: "Intake Air Temperature_7E2",
    shortName: "IAT_7E2",
    modeAndPid: "2101",
    equation: "C - 40",
    min: -40,
    max: 140,
    units: "C",
    header: "7E2",
  },
  {
    name: "Ambient temperature",
    shortName: "ambient",
    modeAndPid: "2101",
    equation: "D - 40",
    min: -40,
    max: 60,
    units: "C",
    header: "7E2",
  },
  {
    name: "Atmosphere Pressure_7E2",
    shortName: "AtmPres_7E2",
    modeAndPid: "2101",
    equation: "E",
    min: 0,
    max: 255,
    units: "kPa",
    header: "7E2",
  },
  {
    name: "Engine Coolant Temperature_7E2",
    shortName: "Coolant_7E2",
    modeAndPid: "2101",
    equation: "F - 40",
    min: -40,
    max: 120,
    units: "C",
    header: "7E2",
  },
  {
    name: "Engine Speed_7E2",
    shortName: "RPM_7E2",
    modeAndPid: "2101",
    equation: "(G * 256 + H) / 4",
    min: 0,
    max: 6000,
    units: "RPM",
    header: "7E2",
  },
  {
    name: "Vehicle Speed_7E2",
    shortName: "KPH_7E2",
    modeAndPid: "2101",
    equation: "I",
    min: 0,
    max: 160,
    units: "km/h",
    header: "7E2",
  },
  {
    name: "Engine run time",
    shortName: "ign time",
    modeAndPid: "2101",
    equation: "J * 256 + K",
    min: 0,
    max: 65535,
    units: "sec.",
    header: "7E2",
  },
  {
    name: "Throttle Position",
    shortName: "Throttle",
    modeAndPid: "2101",
    equation: "L * 20 / 51",
    min: 0,
    max: 100,
    units: "%",
    header: "7E2",
  },
  {
    name: "Accel Pedal Pos #1",
    shortName: "AP1",
    modeAndPid: "2101",
    equation: "M * 20 / 51",
    min: 0,
    max: 100,
    units: "%",
    header: "7E2",
  },
  {
    name: "Accel Pedal Pos #2",
    shortName: "AP2",
    modeAndPid: "2101",
    equation: "N * 20 / 51",
    min: 0,
    max: 100,
    units: "%",
    header: "7E2",
  },
  {
    name: "DTC Clear Warm Up",
    shortName: "DTC warm",
    modeAndPid: "2101",
    equation: "O",
    min: 0,
    max: 255,
    units: "",
    header: "7E2",
  },
  {
    name: "DTC Clear Run Distance",
    shortName: "DTC dist",
    modeAndPid: "2101",
    equation: "P * 256 + Q",
    min: 0,
    max: 65535,
    units: "km",
    header: "7E2",
  },
  {
    name: "DTC Clear Min",
    shortName: "DTC time",
    modeAndPid: "2101",
    equation: "R * 256 + S",
    min: 0,
    max: 65535,
    units: "minutes",
    header: "7E2",
  },
  {
    name: "+B",
    shortName: "+B",
    modeAndPid: "2101",
    equation: "(T * 256 + U) / 1000",
    min: 0,
    max: 16,
    units: "V",
    header: "7E2",
  },
  {
    name: "State of Charge (All Bat)",
    shortName: "SOC (All)",
    modeAndPid: "2101",
    equation: "V * 20 / 51",
    min: 30,
    max: 90,
    units: "%",
    header: "7E2",
  },
  {
    name: "CCS Vehicle Spd",
    shortName: "CCS Spd",
    modeAndPid: "2121",
    equation: "A",
    min: 0,
    max: 200,
    units: "km/h",
    header: "7E2",
  },
  {
    name: "CCS Mem Vehicle Spd",
    shortName: "Mem Spd",
    modeAndPid: "2121",
    equation: "B",
    min: 0,
    max: 200,
    units: "km/h",
    header: "7E2",
  },
  {
    name: "Cruise Operation Status",
    shortName: "Op Stat",
    modeAndPid: "2121",
    equation: "{D:7}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7E2",
  },
  {
    name: "Cruise Control",
    shortName: "CC",
    modeAndPid: "2121",
    equation: "{D:6}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7E2",
  },
  {
    name: "RES/ACC Switch",
    shortName: "RES/ACC",
    modeAndPid: "2121",
    equation: "{E:4}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7E2",
  },
  {
    name: "SET/COAST Switch",
    shortName: "SET/COAST",
    modeAndPid: "2121",
    equation: "{E:3}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7E2",
  },
  {
    name: "Cancel Switch",
    shortName: "Cancel",
    modeAndPid: "2121",
    equation: "{E:2}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7E2",
  },
  {
    name: "Shift Sensor Main",
    shortName: "Shift M",
    modeAndPid: "2141",
    equation: "A * 4.98 / 255",
    min: 0,
    max: 4.98,
    units: "V",
    header: "7E2",
  },
  {
    name: "Shift Sensor Sub",
    shortName: "Shift S",
    modeAndPid: "2141",
    equation: "B * 4.98 / 255",
    min: 0,
    max: 4.98,
    units: "V",
    header: "7E2",
  },
  {
    name: "Shift Sensor Select Main",
    shortName: "Shift Sel M",
    modeAndPid: "2141",
    equation: "C * 4.98 / 255",
    min: 0,
    max: 4.98,
    units: "V",
    header: "7E2",
  },
  {
    name: "Shift Sensor Select Sub",
    shortName: "Shift Sel S",
    modeAndPid: "2141",
    equation: "D * 4.98 / 255",
    min: 0,
    max: 4.98,
    units: "V",
    header: "7E2",
  },
  {
    name: "Auxiliary Battery Temperature",
    shortName: "Aux. B t",
    modeAndPid: "2141",
    equation: "E - 40",
    min: -40,
    max: 120,
    units: "C",
    header: "7E2",
  },
  {
    name: "Engine Rev (Sensor)",
    shortName: "RPM sensor",
    modeAndPid: "2141",
    equation: "(F * 256 + G) / 4",
    min: 0,
    max: 16383.75,
    units: "RPM",
    header: "7E2",
  },
  {
    name: "P Pos SW Terminal Vol",
    shortName: "P Pos Volt",
    modeAndPid: "2141",
    equation: "H * 79.9987793 / 255",
    min: 0,
    max: 79.9987793,
    units: "V",
    header: "7E2",
  },
  {
    name: "MG1 temperature",
    shortName: "MG1t",
    modeAndPid: "2161",
    equation: "A - 40",
    min: -40,
    max: 120,
    units: "C",
    header: "7E2",
  },
  {
    name: "MG1 temperature after IG-ON",
    shortName: "MG1t Ign",
    modeAndPid: "2161",
    equation: "B - 40",
    min: -40,
    max: 120,
    units: "C",
    header: "7E2",
  },
  {
    name: "MG1 temperature Max",
    shortName: "MG1t max",
    modeAndPid: "2161",
    equation: "C - 40",
    min: -40,
    max: 120,
    units: "C",
    header: "7E2",
  },
  {
    name: "MG1 revolution",
    shortName: "MG1 rpm",
    modeAndPid: "2161",
    equation: "D * 256 + E - 32768",
    min: -15000,
    max: 15000,
    units: "RPM",
    header: "7E2",
  },
  {
    name: "MG2 temperature",
    shortName: "MG2t",
    modeAndPid: "2162",
    equation: "A - 40",
    min: -40,
    max: 120,
    units: "C",
    header: "7E2",
  },
  {
    name: "MG2 temperature after IG-ON",
    shortName: "MG2t Ign",
    modeAndPid: "2162",
    equation: "B - 40",
    min: -40,
    max: 120,
    units: "C",
    header: "7E2",
  },
  {
    name: "MG2 temperature Max",
    shortName: "MG2t max",
    modeAndPid: "2162",
    equation: "C - 40",
    min: -40,
    max: 120,
    units: "C",
    header: "7E2",
  },
  {
    name: "MG2 revolution",
    shortName: "MG2 rpm",
    modeAndPid: "2162",
    equation: "D * 256 + E - 32768",
    min: -500,
    max: 15000,
    units: "RPM",
    header: "7E2",
  },
  {
    name: "MG1 torque",
    shortName: "MG1 Torq",
    modeAndPid: "2167",
    equation: "(A * 256 + B) / 8 - 4096",
    min: -4096,
    max: 4095.875,
    units: "Nm",
    header: "7E2",
  },
  {
    name: "MG1 torque execution value",
    shortName: "MG1 E Torq",
    modeAndPid: "2167",
    equation: "(C * 256 + D) / 8 - 4096",
    min: -4096,
    max: 4095.875,
    units: "Nm",
    header: "7E2",
  },
  {
    name: "MG1 Control Mode (PWM=0,Variable PWM=1,Rectangular wave=2)",
    shortName: "MG1 mode",
    modeAndPid: "2167",
    equation: "E",
    min: 0,
    max: 2,
    units: "",
    header: "7E2",
  },
  {
    name: "MG2 torque",
    shortName: "MG2 Torq",
    modeAndPid: "2168",
    equation: "(A * 256 + B) / 8 - 4096",
    min: -4096,
    max: 4095.875,
    units: "Nm",
    header: "7E2",
  },
  {
    name: "MG2 torque execution value",
    shortName: "MG2 E Torq",
    modeAndPid: "2168",
    equation: "(C * 256 + D) / 8 - 4096",
    min: -4096,
    max: 4095.875,
    units: "Nm",
    header: "7E2",
  },
  {
    name: "MG2 Control Mode (PWM=0,Variable PWM=1,Rectangular wave=2)",
    shortName: "MG2 mode",
    modeAndPid: "2168",
    equation: "E",
    min: 0,
    max: 2,
    units: "",
    header: "7E2",
  },
  {
    name: "Inverter MG1 Temp",
    shortName: "Inv1t",
    modeAndPid: "2170",
    equation: "A - 40",
    min: 15,
    max: 150,
    units: "C",
    header: "7E2",
  },
  {
    name: "Inverter MG1 Temp after IG-ON",
    shortName: "Inv1t Ign",
    modeAndPid: "2170",
    equation: "B - 40",
    min: 15,
    max: 150,
    units: "C",
    header: "7E2",
  },
  {
    name: "Inverter MG1 Temp Max",
    shortName: "Inv1t max",
    modeAndPid: "2170",
    equation: "C - 40",
    min: 15,
    max: 150,
    units: "C",
    header: "7E2",
  },
  {
    name: "MG1 Gate Status",
    shortName: "MG1 Gate",
    modeAndPid: "2170",
    equation: "{D:7}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7E2",
  },
  {
    name: "Inverter MG2 Temp",
    shortName: "Inv2t",
    modeAndPid: "2171",
    equation: "A - 40",
    min: 15,
    max: 150,
    units: "C",
    header: "7E2",
  },
  {
    name: "Inverter MG2 Temp after IG-ON",
    shortName: "Inv2t Ign",
    modeAndPid: "2171",
    equation: "B - 40",
    min: 15,
    max: 150,
    units: "C",
    header: "7E2",
  },
  {
    name: "Inverter MG2 Temp Max",
    shortName: "Inv2t max",
    modeAndPid: "2171",
    equation: "C - 40",
    min: 15,
    max: 150,
    units: "C",
    header: "7E2",
  },
  {
    name: "MG2 Gate Status",
    shortName: "MG2 Gate",
    modeAndPid: "2171",
    equation: "{D:7}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7E2",
  },
  {
    name: "Boost converter temperature (upper)",
    shortName: "BC U",
    modeAndPid: "2174",
    equation: "A - 40",
    min: 15,
    max: 150,
    units: "C",
    header: "7E2",
  },
  {
    name: "Boost converter temperature (lower)",
    shortName: "BC L",
    modeAndPid: "2174",
    equation: "B - 40",
    min: 15,
    max: 150,
    units: "C",
    header: "7E2",
  },
  {
    name: "Boost converter temperature after IG-ON",
    shortName: "BC Ign",
    modeAndPid: "2174",
    equation: "C - 40",
    min: 15,
    max: 150,
    units: "C",
    header: "7E2",
  },
  {
    name: "Boost converter temperature Max",
    shortName: "BC max",
    modeAndPid: "2174",
    equation: "D - 40",
    min: 15,
    max: 150,
    units: "C",
    header: "7E2",
  },
  {
    name: "Converter Gate Status",
    shortName: "Cnv Gate",
    modeAndPid: "2174",
    equation: "{E:7}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7E2",
  },
  {
    name: "Overvoltage Input to Converter",
    shortName: "O/V I/P Cnv",
    modeAndPid: "2174",
    equation: "{E:6}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7E2",
  },
  {
    name: "Overvoltage Input to Inverter",
    shortName: "O/V I/P Inv",
    modeAndPid: "2174",
    equation: "{E:5}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7E2",
  },
  {
    name: "VL-Voltage before Boosting",
    shortName: "VLB",
    modeAndPid: "2174",
    equation: "(F * 256 + G) / 2",
    min: 0,
    max: 300,
    units: "V",
    header: "7E2",
  },
  {
    name: "VH-Voltage after Boosting",
    shortName: "VHB",
    modeAndPid: "2174",
    equation: "(H * 256 + I) / 2",
    min: 0,
    max: 765,
    units: "V",
    header: "7E2",
  },
  {
    name: "Prohibit DC/DC converter signal",
    shortName: "P DCDC",
    modeAndPid: "2175",
    equation: "{A:6}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7E2",
  },
  {
    name: "Aircon Gate Status",
    shortName: "A/C Gate",
    modeAndPid: "2175",
    equation: "{A:5}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7E2",
  },
  {
    name: "Water Pump Running",
    shortName: "WP run",
    modeAndPid: "2175",
    equation: "{A:4}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7E2",
  },
  {
    name: "Inverter Water Pump Revolution",
    shortName: "Inv WP",
    modeAndPid: "2175",
    equation: "B * 256 + C",
    min: 0,
    max: 5000,
    units: "RPM",
    header: "7E2",
  },
  {
    name: "Inverter Coolant Temp",
    shortName: "Inv Coolant",
    modeAndPid: "2175",
    equation: "D - 40",
    min: 15,
    max: 150,
    units: "C",
    header: "7E2",
  },
  {
    name: "MG1 Inverter Shutdown",
    shortName: "Inv1 S/D",
    modeAndPid: "2178",
    equation: "{A:7}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7E2",
  },
  {
    name: "MG1 Inverter Fail",
    shortName: "Inv1 fail",
    modeAndPid: "2178",
    equation: "{A:6}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7E2",
  },
  {
    name: "MG2 Inverter Shutdown",
    shortName: "Inv2 S/D",
    modeAndPid: "2178",
    equation: "{B:7}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7E2",
  },
  {
    name: "MG2 Inverter Fail",
    shortName: "Inv2 fail",
    modeAndPid: "2178",
    equation: "{B:6}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7E2",
  },
  {
    name: "DCDC Cnv Target Pulse Duty",
    shortName: "DCTPD",
    modeAndPid: "2179",
    equation: "(A * 256 + B) * 399.9 / 65535",
    min: 0,
    max: 100,
    units: "%",
    header: "7E2",
  },
  {
    name: "Water Pump Run Control Duty",
    shortName: "WP Duty",
    modeAndPid: "2179",
    equation: "C * 6.25",
    min: 0,
    max: 100,
    units: "%",
    header: "7E2",
  },
  {
    name: "Converter Shutdown",
    shortName: "Cnv S/D",
    modeAndPid: "2179",
    equation: "{D:7}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7E2",
  },
  {
    name: "Converter Fail",
    shortName: "Cnv fail",
    modeAndPid: "2179",
    equation: "{D:6}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7E2",
  },
  {
    name: "MG1 Carrier Frequency",
    shortName: "MG1 CF",
    modeAndPid: "217C",
    equation: "A / 20",
    min: 0.75,
    max: 10,
    units: "kHz",
    header: "7E2",
  },
  {
    name: "MG2 Carrier Frequency",
    shortName: "MG2 CF",
    modeAndPid: "217C",
    equation: "B / 20",
    min: 0.75,
    max: 10,
    units: "kHz",
    header: "7E2",
  },
  {
    name: "Boost Ratio",
    shortName: "B Ratio",
    modeAndPid: "217D",
    equation: "A / 2",
    min: 0,
    max: 100,
    units: "%",
    header: "7E2",
  },
  {
    name: "Converter Carrier Frequency (9.55kHz=0,9.13kHz=1,8.71kHz=2,8.29kHz=3,7.87kHz=4,7.45kHz=5,4.8kHz=6)",
    shortName: "Cnv CF",
    modeAndPid: "217D",
    equation: "B",
    min: 0,
    max: 6,
    units: "",
    header: "7E2",
  },
  {
    name: "A/C consumption power",
    shortName: "A/C pwr",
    modeAndPid: "217D",
    equation: "C * 50",
    min: 0,
    max: 5000,
    units: "Watts",
    header: "7E2",
  },
  {
    name: "Battery Block Voltage -V01",
    shortName: "V01",
    modeAndPid: "2181",
    equation: "(A * 256 + B) * 79.99 / 65535",
    min: 12,
    max: 20,
    units: "V",
    header: "7E2",
  },
  {
    name: "Battery Block Voltage -V02",
    shortName: "V02",
    modeAndPid: "2181",
    equation: "(C * 256 + D) * 79.99 / 65535",
    min: 12,
    max: 20,
    units: "V",
    header: "7E2",
  },
  {
    name: "Battery Block Voltage -V03",
    shortName: "V03",
    modeAndPid: "2181",
    equation: "(E * 256 + F) * 79.99 / 65535",
    min: 12,
    max: 20,
    units: "V",
    header: "7E2",
  },
  {
    name: "Battery Block Voltage -V04",
    shortName: "V04",
    modeAndPid: "2181",
    equation: "(G * 256 + H) * 79.99 / 65535",
    min: 12,
    max: 20,
    units: "V",
    header: "7E2",
  },
  {
    name: "Battery Block Voltage -V05",
    shortName: "V05",
    modeAndPid: "2181",
    equation: "(I * 256 + J) * 79.99 / 65535",
    min: 12,
    max: 20,
    units: "V",
    header: "7E2",
  },
  {
    name: "Battery Block Voltage -V06",
    shortName: "V06",
    modeAndPid: "2181",
    equation: "(K * 256 + L) * 79.99 / 65535",
    min: 12,
    max: 20,
    units: "V",
    header: "7E2",
  },
  {
    name: "Battery Block Voltage -V07",
    shortName: "V07",
    modeAndPid: "2181",
    equation: "(M * 256 + N) * 79.99 / 65535",
    min: 12,
    max: 20,
    units: "V",
    header: "7E2",
  },
  {
    name: "Battery Block Voltage -V08",
    shortName: "V08",
    modeAndPid: "2181",
    equation: "(O * 256 + P) * 79.99 / 65535",
    min: 12,
    max: 20,
    units: "V",
    header: "7E2",
  },
  {
    name: "Battery Block Voltage -V09",
    shortName: "V09",
    modeAndPid: "2181",
    equation: "(Q * 256 + R) * 79.99 / 65535",
    min: 12,
    max: 20,
    units: "V",
    header: "7E2",
  },
  {
    name: "Battery Block Voltage -V10",
    shortName: "V10",
    modeAndPid: "2181",
    equation: "(S * 256 + T) * 79.99 / 65535",
    min: 12,
    max: 20,
    units: "V",
    header: "7E2",
  },
  {
    name: "Battery Block Voltage -V11",
    shortName: "V11",
    modeAndPid: "2181",
    equation: "(U * 256 + V) * 79.99 / 65535",
    min: 12,
    max: 20,
    units: "V",
    header: "7E2",
  },
  {
    name: "Battery Block Voltage -V12",
    shortName: "V12",
    modeAndPid: "2181",
    equation: "(W * 256 + X) * 79.99 / 65535",
    min: 12,
    max: 20,
    units: "V",
    header: "7E2",
  },
  {
    name: "Battery Block Voltage -V13",
    shortName: "V13",
    modeAndPid: "2181",
    equation: "(Y * 256 + Z) * 79.99 / 65535",
    min: 12,
    max: 20,
    units: "V",
    header: "7E2",
  },
  {
    name: "Battery Block Voltage -V14",
    shortName: "V14",
    modeAndPid: "2181",
    equation: "(AA * 256 + AB) * 79.99 / 65535",
    min: 12,
    max: 20,
    units: "V",
    header: "7E2",
  },
  {
    name: "Auxiliary Battery Voltage",
    shortName: "Aux Bty",
    modeAndPid: "2181",
    equation: "(AC * 256 + AD) * 79.9 / 65535 - 40",
    min: 0,
    max: 16,
    units: "V",
    header: "7E2",
  },
  {
    name: "Power Resource VB",
    shortName: "VB",
    modeAndPid: "2181",
    equation: "(AE * 256 + AF) / 10",
    min: 150,
    max: 300,
    units: "V",
    header: "7E2",
  },
  {
    name: "VMF Fan Motor Voltage1",
    shortName: "VMF1",
    modeAndPid: "2181",
    equation: "AG / 10",
    min: 0,
    max: 16,
    units: "V",
    header: "7E2",
  },
  {
    name: "HV battery intake air temperature",
    shortName: "TB Intake",
    modeAndPid: "2187",
    equation: "(A * 256 + B) * 255.9 / 65535 - 50",
    min: -50,
    max: 60,
    units: "C",
    header: "7E2",
  },
  {
    name: "Temp of Batt TB1",
    shortName: "TB 1",
    modeAndPid: "2187",
    equation: "(C * 256 + D) * 255.9 / 65535 - 50",
    min: -50,
    max: 60,
    units: "C",
    header: "7E2",
  },
  {
    name: "Temp of Batt TB2",
    shortName: "TB 2",
    modeAndPid: "2187",
    equation: "(E * 256 + F) * 255.9 / 65535 - 50",
    min: -50,
    max: 60,
    units: "C",
    header: "7E2",
  },
  {
    name: "Temp of Batt TB3",
    shortName: "TB 3",
    modeAndPid: "2187",
    equation: "(G * 256 + H) * 255.9 / 65535 - 50",
    min: -50,
    max: 60,
    units: "C",
    header: "7E2",
  },
  {
    name: "Power Resource IB",
    shortName: "IB",
    modeAndPid: "218A",
    equation: "(A * 256 + B) / 100 - 327.68",
    min: -200,
    max: 200,
    units: "Amperes",
    header: "7E2",
  },
  {
    name: "Cooling Fan 0",
    shortName: "C Fan 0",
    modeAndPid: "218E",
    equation: "A / 2",
    min: 0,
    max: 100,
    units: "%",
    header: "7E2",
  },
  {
    name: "Cooling Fan Relay Status",
    shortName: "C Fan Rly",
    modeAndPid: "218E",
    equation: "{B:7}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7E2",
  },
  {
    name: "Battery block minimum voltage",
    shortName: "Vmin",
    modeAndPid: "2192",
    equation: "(A * 256 + B) * 79.99 / 65535",
    min: 12,
    max: 20,
    units: "V",
    header: "7E2",
  },
  {
    name: "Battery block number with minimum voltage",
    shortName: "Blk# min",
    modeAndPid: "2192",
    equation: "C + 1",
    min: 1,
    max: 14,
    units: "",
    header: "7E2",
  },
  {
    name: "Battery block maximum voltage",
    shortName: "Vmax",
    modeAndPid: "2192",
    equation: "(D * 256 + E) * 79.99 / 65535",
    min: 12,
    max: 20,
    units: "V",
    header: "7E2",
  },
  {
    name: "Battery block number with maximum voltage",
    shortName: "Blk# max",
    modeAndPid: "2192",
    equation: "F + 1",
    min: 1,
    max: 14,
    units: "",
    header: "7E2",
  },
  {
    name: "Difference between maximum & minimum voltage",
    shortName: "Vmax-Vmin",
    modeAndPid: "2192",
    equation: "((D - A) * 256 + E - B) * 79.99 / 65535",
    min: 0,
    max: 2,
    units: "V",
    header: "7E2",
  },
  {
    name: "Number of battery blocks",
    shortName: "#Bty Blk",
    modeAndPid: "2192",
    equation: "G",
    min: 14,
    max: 14,
    units: "",
    header: "7E2",
  },
  {
    name: "Accumulated Time of Battery Low",
    shortName: "Low count",
    modeAndPid: "2192",
    equation: "H * 256 + I",
    min: 0,
    max: 65535,
    units: "",
    header: "7E2",
  },
  {
    name: "Accumulated Time of DC Inhibit",
    shortName: "DCI count",
    modeAndPid: "2192",
    equation: "J * 256 + K",
    min: 0,
    max: 65535,
    units: "",
    header: "7E2",
  },
  {
    name: "Accumulated Time of Battery too High",
    shortName: "High count",
    modeAndPid: "2192",
    equation: "L * 256 + M",
    min: 0,
    max: 65535,
    units: "",
    header: "7E2",
  },
  {
    name: "Accumulated Time of Hot Temperature",
    shortName: "Hot count",
    modeAndPid: "2192",
    equation: "N * 256 + O",
    min: 0,
    max: 65535,
    units: "",
    header: "7E2",
  },
  {
    name: "Internal Resistance R01",
    shortName: "R01",
    modeAndPid: "2195",
    equation: "A / 1000",
    min: 0,
    max: 0.255,
    units: "ohm",
    header: "7E2",
  },
  {
    name: "Internal Resistance R02",
    shortName: "R02",
    modeAndPid: "2195",
    equation: "B / 1000",
    min: 0,
    max: 0.255,
    units: "ohm",
    header: "7E2",
  },
  {
    name: "Internal Resistance R03",
    shortName: "R03",
    modeAndPid: "2195",
    equation: "C / 1000",
    min: 0,
    max: 0.255,
    units: "ohm",
    header: "7E2",
  },
  {
    name: "Internal Resistance R04",
    shortName: "R04",
    modeAndPid: "2195",
    equation: "D / 1000",
    min: 0,
    max: 0.255,
    units: "ohm",
    header: "7E2",
  },
  {
    name: "Internal Resistance R05",
    shortName: "R05",
    modeAndPid: "2195",
    equation: "E / 1000",
    min: 0,
    max: 0.255,
    units: "ohm",
    header: "7E2",
  },
  {
    name: "Internal Resistance R06",
    shortName: "R06",
    modeAndPid: "2195",
    equation: "F / 1000",
    min: 0,
    max: 0.255,
    units: "ohm",
    header: "7E2",
  },
  {
    name: "Internal Resistance R07",
    shortName: "R07",
    modeAndPid: "2195",
    equation: "G / 1000",
    min: 0,
    max: 0.255,
    units: "ohm",
    header: "7E2",
  },
  {
    name: "Internal Resistance R08",
    shortName: "R08",
    modeAndPid: "2195",
    equation: "H / 1000",
    min: 0,
    max: 0.255,
    units: "ohm",
    header: "7E2",
  },
  {
    name: "Internal Resistance R09",
    shortName: "R09",
    modeAndPid: "2195",
    equation: "I / 1000",
    min: 0,
    max: 0.255,
    units: "ohm",
    header: "7E2",
  },
  {
    name: "Internal Resistance R10",
    shortName: "R10",
    modeAndPid: "2195",
    equation: "J / 1000",
    min: 0,
    max: 0.255,
    units: "ohm",
    header: "7E2",
  },
  {
    name: "Internal Resistance R11",
    shortName: "R11",
    modeAndPid: "2195",
    equation: "K / 1000",
    min: 0,
    max: 0.255,
    units: "ohm",
    header: "7E2",
  },
  {
    name: "Internal Resistance R12",
    shortName: "R12",
    modeAndPid: "2195",
    equation: "L / 1000",
    min: 0,
    max: 0.255,
    units: "ohm",
    header: "7E2",
  },
  {
    name: "Internal Resistance R13",
    shortName: "R13",
    modeAndPid: "2195",
    equation: "M / 1000",
    min: 0,
    max: 0.255,
    units: "ohm",
    header: "7E2",
  },
  {
    name: "Internal Resistance R14",
    shortName: "R14",
    modeAndPid: "2195",
    equation: "N / 1000",
    min: 0,
    max: 0.255,
    units: "ohm",
    header: "7E2",
  },
  {
    name: "Batt Pack Current Val",
    shortName: "Bty Curr",
    modeAndPid: "2198",
    equation: "(A * 256 + B) / 100 - 327.68",
    min: -200,
    max: 200,
    units: "Amperes",
    header: "7E2",
  },
  {
    name: "HV battery charge control",
    shortName: "Chg ctrl",
    modeAndPid: "2198",
    equation: "C / 2 - 64",
    min: -40,
    max: 0,
    units: "kW",
    header: "7E2",
  },
  {
    name: "HV battery discharge control",
    shortName: "Dischg ctrl",
    modeAndPid: "2198",
    equation: "D / 2 - 64",
    min: 0,
    max: 40,
    units: "kW",
    header: "7E2",
  },
  {
    name: "Delta SOC",
    shortName: "Delta SOC",
    modeAndPid: "2198",
    equation: "E / 2",
    min: 0,
    max: 100,
    units: "%",
    header: "7E2",
  },
  {
    name: "SOC after IG-ON",
    shortName: "SOC ig-on",
    modeAndPid: "2198",
    equation: "F / 2",
    min: 30,
    max: 90,
    units: "%",
    header: "7E2",
  },
  {
    name: "SOC Max",
    shortName: "SOC max",
    modeAndPid: "2198",
    equation: "G / 2",
    min: 30,
    max: 90,
    units: "%",
    header: "7E2",
  },
  {
    name: "SOC Min",
    shortName: "SOC min",
    modeAndPid: "2198",
    equation: "H / 2",
    min: 30,
    max: 90,
    units: "%",
    header: "7E2",
  },
  {
    name: "ECU Control Mode (Driving control mode=1,Current sensor offset mode=2,External charge control mode=3,Power supply end mode=4)",
    shortName: "ECU mode",
    modeAndPid: "219B",
    equation: "A",
    min: 1,
    max: 4,
    units: "",
    header: "7E2",
  },
  {
    name: "Cooling Fan Mode 1",
    shortName: "Fan Mode",
    modeAndPid: "219B",
    equation: "B",
    min: 0,
    max: 6,
    units: "",
    header: "7E2",
  },
  {
    name: "Standby Blower Request Status",
    shortName: "SBRS",
    modeAndPid: "219B",
    equation: "{C:7}",
    min: 0,
    max: 1,
    units: "Off/On",
    header: "7E2",
  },
  {
    name: "Short Circuit Wave Highest Value",
    shortName: "S/C Wave Hi",
    modeAndPid: "219B",
    equation: "D * 4.98 / 255",
    min: 0,
    max: 4.98,
    units: "V",
    header: "7E2",
  },
  {
    name: "Model Code_7E2",
    shortName: "MCode_7E2",
    modeAndPid: "21C1",
    equation: "ABCDEFG",
    min: 0,
    max: 0,
    units: "",
    header: "7E2",
  },
  {
    name: "Engine Code (P410)",
    shortName: "Eng Code",
    modeAndPid: "21C1",
    equation: "HIJKLM",
    min: 0,
    max: 0,
    units: "",
    header: "7E2",
  },
  {
    name: "Destination (America=A=65)",
    shortName: "Dest",
    modeAndPid: "21C1",
    equation: "P",
    min: 0,
    max: 0,
    units: "",
    header: "7E2",
  },
  {
    name: "ECU Code",
    shortName: "ECU Code",
    modeAndPid: "21C2",
    equation: "ABCDE",
    min: 0,
    max: 0,
    units: "",
    header: "7E2",
  },
  {
    name: "Number of Current Code",
    shortName: "#Curr Code",
    modeAndPid: "21E1",
    equation: "A",
    min: 0,
    max: 255,
    units: "",
    header: "7E2",
  },
  {
    name: "Number of History Code",
    shortName: "#Hist Code",
    modeAndPid: "21E1",
    equation: "B",
    min: 0,
    max: 255,
    units: "",
    header: "7E2",
  },
];

function sanitizeIdPart(input: string): string {
  const s = String(input ?? '').trim().toUpperCase();
  const cleaned = s.replace(/[^A-Z0-9]+/g, '_').replace(/^_+|_+$/g, '');
  return cleaned.length > 0 ? cleaned : 'X';
}

export const PRIUSCHAT_METRIC_PIDS: Record<string, PidDefinition> = (() => {
  const out: Record<string, PidDefinition> = {};
  for (const row of PRIUSCHAT_METRIC_ROWS) {
    const baseId = `PC_${row.header}_${row.modeAndPid}_${sanitizeIdPart(row.shortName)}`;
    let pid = baseId;
    let n = 2;
    while (out[pid]) {
      pid = `${baseId}_${n++}`;
    }

    out[pid] = {
      pid,
      request: row.modeAndPid,
      header: row.header,
      name: row.name,
      shortName: row.shortName,
      unit: row.units,
      min: row.min,
      max: row.max,
      decode: compileTorqueEquation(row.equation),
    };
  }
  return out;
})();

export const PRIUSCHAT_METRIC_PID_IDS = Object.keys(PRIUSCHAT_METRIC_PIDS);
